name: AI Code Review

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # ✅ Don't quote numbers

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        working-directory: ./code_Reviewer
        run: npm install

      - name: Generate PR diff
        run: |
          git fetch origin main
          git diff origin/main...HEAD > code_Reviewer/pr.diff

      - name: Run AI Review script
        working-directory: ./code_Reviewer
        run: node app_review.js
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
