# .github/workflows/ai-review.yml
name: AI Code Review

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR code
        uses: actions/checkout@v3

      - name: Send PR diff to AI backend
        run: |
          git diff origin/main...HEAD > pr.diff
          curl -X POST https://your-ai-api/review \
            -H "Content-Type: text/plain" \
            --data-binary @pr.diff
